# Generated by Django 5.2.12 on 2026-03-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fifty_two_week_high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='fifty_two_week_low',
            field=models.FloatField(default=0),
        ),
    ]
