# Generated by Django 5.2.12 on 2026-03-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_stock_fifty_two_week_high_stock_fifty_two_week_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
