# Generated by Django 5.2.12 on 2026-03-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_stock_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='predicted_change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='predicted_price',
            field=models.FloatField(default=0),
        ),
    ]
