# Generated by Django 5.2.12 on 2026-03-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_stock_predicted_change_stock_predicted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='signal',
            field=models.CharField(default='Hold', max_length=50),
        ),
    ]
