name: Zeus CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            git pull origin main

            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            deactivate
            cd ..

            cd frontend
            npm install
            npm run build
            cd ..

            pm2 restart all
